name: Test Moodle URL Access

on:
  workflow_dispatch:

jobs:
  test-access:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Moodle URL
        env:
          ICAL_URL: ${{ secrets.ICAL_URL }}
        run: |
          curl -v --max-time 15 "$ICAL_URL" || echo "Request failed or timed out"

